name: workflow demonstration
on: [push]
jobs:
  build:
    name: Verify build
    working-directory: ./Source
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Source
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - run: dotnet build
